### ISSUE TITLE
KeyError: 'InstantIDModelLoader'

### ISSUE THREAD

**Issue by bytonylee** [fofr/cog-face-to-sticker#7]
To build the avatar-generator in my workflow, I'm now testing comfyui template for replicate.
So I try this and cog-face-to-many from you.

I did 
1. git clone --recurse-submodules https://github.com/fofr/cog-face-to-sticker.git
2. ./scripts/clone_plugins.sh
with the flow to push on replicate.

But when I clone and try 'predict' it without any change from original code, error below is happened.

```shell
Running workflow
got prompt
Error handling request
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/src/ComfyUI/server.py", line 47, in cache_control
response: web.Response = await handler(request)
File "/src/ComfyUI/server.py", line 474, in post_prompt
valid = execution.validate_prompt(prompt)
File "/src/ComfyUI/execution.py", line 620, in validate_prompt
class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'InstantIDModelLoader'
ComfyUI error: 500 Internal Server Error
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
File "/src/predict.py", line 167, in predict
self.comfyUI.run_workflow(wf)
File "/src/helpers/comfyui.py", line 233, in run_workflow
prompt_id = self.queue_prompt(workflow)
File "/src/helpers/comfyui.py", line 174, in queue_prompt
raise Exception(
Exception: ComfyUI Error – Your workflow could not be run. This usually happens if you’re trying to use an unsupported node. Check the logs for 'KeyError: ' details, and go to https://github.com/fofr/cog-comfyui to see the list of supported custom nodes.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b6b1e]

goroutine 1 [running]:
github.com/replicate/cog/pkg/cli.handleMultipleFileOutput(0x9315c0?, 0xc0003d3170?)
        /home/runner/work/cog/cog/pkg/cli/predict.go:268 +0x1e
github.com/replicate/cog/pkg/cli.predictIndividualInputs({{{0x0, 0x0, 0x0}, {0xc000312e50, 0x1, 0x1}, {0x9a3784, 0x3}, {0xc00014b578, 0x18}, ...}, ...}, ...)
        /home/runner/work/cog/cog/pkg/cli/predict.go:192 +0x227
github.com/replicate/cog/pkg/cli.cmdPredict(0xc00017ea00?, {0xc0002a75e0?, 0x4?, 0x9a39cb?})
        /home/runner/work/cog/cog/pkg/cli/predict.go:165 +0xae5
github.com/spf13/cobra.(*Command).execute(0xc0002aaf00, {0xc0002a75c0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002aa000)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc00022ff30?)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
        /home/runner/work/cog/cog/cmd/cog/cog.go:14 +0x66
```

**Comment by spoonknight** [comment]
can you resolve it ?
