### ISSUE TITLE
KeyError: 'InstantIDModelLoader'

### ISSUE THREAD

**Issue by spoonknight** [fofr/cog-face-to-sticker#9]
Random seed set to: 3684869475
Checking inputs
✅ /tmp/inputs/input.png
====================================
Running workflow
got prompt
Error handling request
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/src/ComfyUI/server.py", line 47, in cache_control
response: web.Response = await handler(request)
File "/src/ComfyUI/server.py", line 474, in post_prompt
valid = execution.validate_prompt(prompt)
File "/src/ComfyUI/execution.py", line 620, in validate_prompt
class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'InstantIDModelLoader'
ComfyUI error: 500 Internal Server Error
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "/src/predict.py", line 167, in predict
self.comfyUI.run_workflow(wf)
File "/src/helpers/comfyui.py", line 233, in run_workflow
prompt_id = self.queue_prompt(workflow)
File "/src/helpers/comfyui.py", line 174, in queue_prompt
raise Exception(
Exception: ComfyUI Error – Your workflow could not be run. This usually happens if you’re trying to use an unsupported node. Check the logs for 'KeyError: ' details, and go to https://github.com/fofr/cog-comfyui to see the list of supported custom nodes.

**Comment by fofr** [comment]
This model uses an earlier version of InstantID, you need to make sure you have the version specified here:
https://github.com/fofr/cog-face-to-sticker/blob/main/scripts/clone_plugins.sh#L14
